if (!require("pacman")) install.packages("pacman")
pacman::p_load(DMwR,ggmap,timeSeries,fPortfolio,maptools,maps,bizdays,plotly, readr, dplyr,tidyr,RColorBrewer,imputeTS,lubridate,stringr,d3heatmap,data.table,ggthemes,scales,formattable,viridis,animation,ggmap,leaflet,gridExtra,showtext,extrafont,plyr,stringi)
library(ggmap);library(maptools);library(maps);library(plotly);library(readr);library(dplyr);
library(tidyr);library(RColorBrewer);library(lubridate);library(stringr);library(d3heatmap);
library(data.table);library(ggthemes);library(scales);library(formattable);library(viridis);
library(animation);library(ggmap);library(leaflet);library(gridExtra);library(showtext);
library(extrafont);library(plyr);library(stringi);library(DMwR);library(Quandl);library(timeSeries); 
library(fPortfolio); library(quantmod); library(caTools);library(PerformanceAnalytics);library(quantmod);
library(imputeTS)


SP500 <- read.csv("https://raw.githubusercontent.com/datasets/s-and-p-500-companies/master/data/constituents-financials.csv", 
                  header=T, 
                  sep=",",
                  stringsAsFactors=FALSE)

TICKERS<-as.vector(SP500$Symbol)
TICKERS[which(TICKERS=="BRK.B")] <- "BRK-B"
TICKERS[which(TICKERS=="BF.B")]<- "BF-B"
TICKERS<- TICKERS[-which(TICKERS=="HAR")]
TICKERS<- TICKERS[-which(TICKERS=="LLTC")]

startDate = as.Date("2017-03-28") #Specify period of time we are interested in
endDate = as.Date("2017-04-01")


for (i in 1:length(TICKERS)) {
  getSymbols(TICKERS[i], from = startDate, to = endDate)
}




#eapply(.GlobalEnv,function(x) cleaning_stocks(x))
eapply(.GlobalEnv,function(x) data.frame(date=index(x), coredata(x)))


cleaning_stocks <- function(stock.xts){
  stock.df<- data.frame(date=index(stock.xts), coredata(stock.xts))
  colnames(stock.df)[2]<- "Open"
  colnames(stock.df)[3]<- "High"
  colnames(stock.df)[4]<- "Low"
  colnames(stock.df)[5]<- "Close"
  colnames(stock.df)[6]<- "Volume"
  colnames(stock.df)[7]<- "Adj.Close"
  return(stock.df)
}



###########################
MMM	<-	cleaning_stocks(	MMM	)
ABT	<-	cleaning_stocks(	ABT	)
ABBV	<-	cleaning_stocks(	ABBV	)
ACN	<-	cleaning_stocks(	ACN	)
ATVI	<-	cleaning_stocks(	ATVI	)
AYI	<-	cleaning_stocks(	AYI	)
ADBE	<-	cleaning_stocks(	ADBE	)
AAP	<-	cleaning_stocks(	AAP	)
AES	<-	cleaning_stocks(	AES	)
AET	<-	cleaning_stocks(	AET	)
AMG	<-	cleaning_stocks(	AMG	)
AFL	<-	cleaning_stocks(	AFL	)
A	<-	cleaning_stocks(	A	)
APD	<-	cleaning_stocks(	APD	)
AKAM	<-	cleaning_stocks(	AKAM	)
ALK	<-	cleaning_stocks(	ALK	)
ALB	<-	cleaning_stocks(	ALB	)
ALXN	<-	cleaning_stocks(	ALXN	)
ALLE	<-	cleaning_stocks(	ALLE	)
AGN	<-	cleaning_stocks(	AGN	)
ADS	<-	cleaning_stocks(	ADS	)
LNT	<-	cleaning_stocks(	LNT	)
ALL	<-	cleaning_stocks(	ALL	)
GOOGL	<-	cleaning_stocks(	GOOGL	)
GOOG	<-	cleaning_stocks(	GOOG	)
MO	<-	cleaning_stocks(	MO	)
AMZN	<-	cleaning_stocks(	AMZN	)
AEE	<-	cleaning_stocks(	AEE	)
AAL	<-	cleaning_stocks(	AAL	)
AEP	<-	cleaning_stocks(	AEP	)
AXP	<-	cleaning_stocks(	AXP	)
AIG	<-	cleaning_stocks(	AIG	)
AMT	<-	cleaning_stocks(	AMT	)
AWK	<-	cleaning_stocks(	AWK	)
AMP	<-	cleaning_stocks(	AMP	)
ABC	<-	cleaning_stocks(	ABC	)
AME	<-	cleaning_stocks(	AME	)
AMGN	<-	cleaning_stocks(	AMGN	)
APH	<-	cleaning_stocks(	APH	)
APC	<-	cleaning_stocks(	APC	)
ADI	<-	cleaning_stocks(	ADI	)
ANTM	<-	cleaning_stocks(	ANTM	)
AON	<-	cleaning_stocks(	AON	)
APA	<-	cleaning_stocks(	APA	)
AIV	<-	cleaning_stocks(	AIV	)
AAPL	<-	cleaning_stocks(	AAPL	)
AMAT	<-	cleaning_stocks(	AMAT	)
ADM	<-	cleaning_stocks(	ADM	)
ARNC	<-	cleaning_stocks(	ARNC	)
AJG	<-	cleaning_stocks(	AJG	)
AIZ	<-	cleaning_stocks(	AIZ	)
T	<-	cleaning_stocks(	T	)
ADSK	<-	cleaning_stocks(	ADSK	)
ADP	<-	cleaning_stocks(	ADP	)
AN	<-	cleaning_stocks(	AN	)
AZO	<-	cleaning_stocks(	AZO	)
AVB	<-	cleaning_stocks(	AVB	)
AVY	<-	cleaning_stocks(	AVY	)
BHI	<-	cleaning_stocks(	BHI	)
BLL	<-	cleaning_stocks(	BLL	)
BAC	<-	cleaning_stocks(	BAC	)
BCR	<-	cleaning_stocks(	BCR	)
BAX	<-	cleaning_stocks(	BAX	)
BBT	<-	cleaning_stocks(	BBT	)
BDX	<-	cleaning_stocks(	BDX	)
BBBY	<-	cleaning_stocks(	BBBY	)
`BRK-B`	<-	cleaning_stocks(	`BRK-B`	)
BBY	<-	cleaning_stocks(	BBY	)
BIIB	<-	cleaning_stocks(	BIIB	)
BLK	<-	cleaning_stocks(	BLK	)
HRB	<-	cleaning_stocks(	HRB	)
BA	<-	cleaning_stocks(	BA	)
BWA	<-	cleaning_stocks(	BWA	)
BXP	<-	cleaning_stocks(	BXP	)
BSX	<-	cleaning_stocks(	BSX	)
BMY	<-	cleaning_stocks(	BMY	)
AVGO	<-	cleaning_stocks(	AVGO	)
`BF-B`	<-	cleaning_stocks(	`BF-B`	)
CHRW	<-	cleaning_stocks(	CHRW	)
CA	<-	cleaning_stocks(	CA	)
COG	<-	cleaning_stocks(	COG	)
CPB	<-	cleaning_stocks(	CPB	)
COF	<-	cleaning_stocks(	COF	)
CAH	<-	cleaning_stocks(	CAH	)
KMX	<-	cleaning_stocks(	KMX	)
CCL	<-	cleaning_stocks(	CCL	)
CAT	<-	cleaning_stocks(	CAT	)
CBOE	<-	cleaning_stocks(	CBOE	)
CBG	<-	cleaning_stocks(	CBG	)
CBS	<-	cleaning_stocks(	CBS	)
CELG	<-	cleaning_stocks(	CELG	)
CNC	<-	cleaning_stocks(	CNC	)
CNP	<-	cleaning_stocks(	CNP	)
CTL	<-	cleaning_stocks(	CTL	)
CERN	<-	cleaning_stocks(	CERN	)
CF	<-	cleaning_stocks(	CF	)
SCHW	<-	cleaning_stocks(	SCHW	)
CHTR	<-	cleaning_stocks(	CHTR	)
CHK	<-	cleaning_stocks(	CHK	)
CVX	<-	cleaning_stocks(	CVX	)
CMG	<-	cleaning_stocks(	CMG	)
CB	<-	cleaning_stocks(	CB	)
CHD	<-	cleaning_stocks(	CHD	)
CI	<-	cleaning_stocks(	CI	)
XEC	<-	cleaning_stocks(	XEC	)
CINF	<-	cleaning_stocks(	CINF	)
CTAS	<-	cleaning_stocks(	CTAS	)
CSCO	<-	cleaning_stocks(	CSCO	)
C	<-	cleaning_stocks(	C	)
CFG	<-	cleaning_stocks(	CFG	)
CTXS	<-	cleaning_stocks(	CTXS	)
CME	<-	cleaning_stocks(	CME	)
CMS	<-	cleaning_stocks(	CMS	)
COH	<-	cleaning_stocks(	COH	)
KO	<-	cleaning_stocks(	KO	)
CTSH	<-	cleaning_stocks(	CTSH	)
CL	<-	cleaning_stocks(	CL	)
CMCSA	<-	cleaning_stocks(	CMCSA	)
CMA	<-	cleaning_stocks(	CMA	)
CAG	<-	cleaning_stocks(	CAG	)
CXO	<-	cleaning_stocks(	CXO	)
COP	<-	cleaning_stocks(	COP	)
ED	<-	cleaning_stocks(	ED	)
STZ	<-	cleaning_stocks(	STZ	)
GLW	<-	cleaning_stocks(	GLW	)
COST	<-	cleaning_stocks(	COST	)
COTY	<-	cleaning_stocks(	COTY	)
CCI	<-	cleaning_stocks(	CCI	)
CSRA	<-	cleaning_stocks(	CSRA	)
CSX	<-	cleaning_stocks(	CSX	)
CMI	<-	cleaning_stocks(	CMI	)
CVS	<-	cleaning_stocks(	CVS	)
DHI	<-	cleaning_stocks(	DHI	)
DHR	<-	cleaning_stocks(	DHR	)
DRI	<-	cleaning_stocks(	DRI	)
DVA	<-	cleaning_stocks(	DVA	)
DE	<-	cleaning_stocks(	DE	)
DLPH	<-	cleaning_stocks(	DLPH	)
DAL	<-	cleaning_stocks(	DAL	)
XRAY	<-	cleaning_stocks(	XRAY	)
DVN	<-	cleaning_stocks(	DVN	)
DLR	<-	cleaning_stocks(	DLR	)
DFS	<-	cleaning_stocks(	DFS	)
DISCA	<-	cleaning_stocks(	DISCA	)
DISCK	<-	cleaning_stocks(	DISCK	)
DG	<-	cleaning_stocks(	DG	)
DLTR	<-	cleaning_stocks(	DLTR	)
D	<-	cleaning_stocks(	D	)
DOV	<-	cleaning_stocks(	DOV	)
DOW	<-	cleaning_stocks(	DOW	)
DPS	<-	cleaning_stocks(	DPS	)
DTE	<-	cleaning_stocks(	DTE	)
DD	<-	cleaning_stocks(	DD	)
DUK	<-	cleaning_stocks(	DUK	)
DNB	<-	cleaning_stocks(	DNB	)
ETFC	<-	cleaning_stocks(	ETFC	)
EMN	<-	cleaning_stocks(	EMN	)
ETN	<-	cleaning_stocks(	ETN	)
EBAY	<-	cleaning_stocks(	EBAY	)
ECL	<-	cleaning_stocks(	ECL	)
EIX	<-	cleaning_stocks(	EIX	)
EW	<-	cleaning_stocks(	EW	)
EA	<-	cleaning_stocks(	EA	)
EMR	<-	cleaning_stocks(	EMR	)
ETR	<-	cleaning_stocks(	ETR	)
EVHC	<-	cleaning_stocks(	EVHC	)
EOG	<-	cleaning_stocks(	EOG	)
EQT	<-	cleaning_stocks(	EQT	)
EFX	<-	cleaning_stocks(	EFX	)
EQIX	<-	cleaning_stocks(	EQIX	)
EQR	<-	cleaning_stocks(	EQR	)
ESS	<-	cleaning_stocks(	ESS	)
EL	<-	cleaning_stocks(	EL	)
ES	<-	cleaning_stocks(	ES	)
EXC	<-	cleaning_stocks(	EXC	)
EXPE	<-	cleaning_stocks(	EXPE	)
EXPD	<-	cleaning_stocks(	EXPD	)
ESRX	<-	cleaning_stocks(	ESRX	)
EXR	<-	cleaning_stocks(	EXR	)
XOM	<-	cleaning_stocks(	XOM	)
FFIV	<-	cleaning_stocks(	FFIV	)
FB	<-	cleaning_stocks(	FB	)
FAST	<-	cleaning_stocks(	FAST	)
FRT	<-	cleaning_stocks(	FRT	)
FDX	<-	cleaning_stocks(	FDX	)
FIS	<-	cleaning_stocks(	FIS	)
FITB	<-	cleaning_stocks(	FITB	)
FSLR	<-	cleaning_stocks(	FSLR	)
FE	<-	cleaning_stocks(	FE	)
FISV	<-	cleaning_stocks(	FISV	)
FLIR	<-	cleaning_stocks(	FLIR	)
FLS	<-	cleaning_stocks(	FLS	)
FLR	<-	cleaning_stocks(	FLR	)
FMC	<-	cleaning_stocks(	FMC	)
FTI	<-	cleaning_stocks(	FTI	)
FL	<-	cleaning_stocks(	FL	)
F	<-	cleaning_stocks(	F	)
FTV	<-	cleaning_stocks(	FTV	)
FBHS	<-	cleaning_stocks(	FBHS	)
BEN	<-	cleaning_stocks(	BEN	)
FCX	<-	cleaning_stocks(	FCX	)
FTR	<-	cleaning_stocks(	FTR	)
GPS	<-	cleaning_stocks(	GPS	)
GRMN	<-	cleaning_stocks(	GRMN	)
GD	<-	cleaning_stocks(	GD	)
GE	<-	cleaning_stocks(	GE	)
GGP	<-	cleaning_stocks(	GGP	)
GIS	<-	cleaning_stocks(	GIS	)
GM	<-	cleaning_stocks(	GM	)
GPC	<-	cleaning_stocks(	GPC	)
GILD	<-	cleaning_stocks(	GILD	)
GPN	<-	cleaning_stocks(	GPN	)
GS	<-	cleaning_stocks(	GS	)
GT	<-	cleaning_stocks(	GT	)
GWW	<-	cleaning_stocks(	GWW	)
HAL	<-	cleaning_stocks(	HAL	)
HBI	<-	cleaning_stocks(	HBI	)
HOG	<-	cleaning_stocks(	HOG	)
HAR	<-	cleaning_stocks(	HAR	)
HRS	<-	cleaning_stocks(	HRS	)
HIG	<-	cleaning_stocks(	HIG	)
HAS	<-	cleaning_stocks(	HAS	)
HCA	<-	cleaning_stocks(	HCA	)
HCP	<-	cleaning_stocks(	HCP	)
HP	<-	cleaning_stocks(	HP	)
HSIC	<-	cleaning_stocks(	HSIC	)
HES	<-	cleaning_stocks(	HES	)
HPE	<-	cleaning_stocks(	HPE	)
HOLX	<-	cleaning_stocks(	HOLX	)
HD	<-	cleaning_stocks(	HD	)
HON	<-	cleaning_stocks(	HON	)
HRL	<-	cleaning_stocks(	HRL	)
HST	<-	cleaning_stocks(	HST	)
HPQ	<-	cleaning_stocks(	HPQ	)
HUM	<-	cleaning_stocks(	HUM	)
HBAN	<-	cleaning_stocks(	HBAN	)
IDXX	<-	cleaning_stocks(	IDXX	)
ITW	<-	cleaning_stocks(	ITW	)
ILMN	<-	cleaning_stocks(	ILMN	)
INCY	<-	cleaning_stocks(	INCY	)
IR	<-	cleaning_stocks(	IR	)
INTC	<-	cleaning_stocks(	INTC	)
ICE	<-	cleaning_stocks(	ICE	)
IBM	<-	cleaning_stocks(	IBM	)
IP	<-	cleaning_stocks(	IP	)
IPG	<-	cleaning_stocks(	IPG	)
IFF	<-	cleaning_stocks(	IFF	)
INTU	<-	cleaning_stocks(	INTU	)
ISRG	<-	cleaning_stocks(	ISRG	)
IVZ	<-	cleaning_stocks(	IVZ	)
IRM	<-	cleaning_stocks(	IRM	)
JBHT	<-	cleaning_stocks(	JBHT	)
JEC	<-	cleaning_stocks(	JEC	)
SJM	<-	cleaning_stocks(	SJM	)
JNJ	<-	cleaning_stocks(	JNJ	)
JCI	<-	cleaning_stocks(	JCI	)
JPM	<-	cleaning_stocks(	JPM	)
JNPR	<-	cleaning_stocks(	JNPR	)
KSU	<-	cleaning_stocks(	KSU	)
K	<-	cleaning_stocks(	K	)
KEY	<-	cleaning_stocks(	KEY	)
KMB	<-	cleaning_stocks(	KMB	)
KIM	<-	cleaning_stocks(	KIM	)
KMI	<-	cleaning_stocks(	KMI	)
KLAC	<-	cleaning_stocks(	KLAC	)
KSS	<-	cleaning_stocks(	KSS	)
KHC	<-	cleaning_stocks(	KHC	)
KR	<-	cleaning_stocks(	KR	)
LB	<-	cleaning_stocks(	LB	)
LLL	<-	cleaning_stocks(	LLL	)
LH	<-	cleaning_stocks(	LH	)
LRCX	<-	cleaning_stocks(	LRCX	)
LEG	<-	cleaning_stocks(	LEG	)
LEN	<-	cleaning_stocks(	LEN	)
LUK	<-	cleaning_stocks(	LUK	)
LVLT	<-	cleaning_stocks(	LVLT	)
LLY	<-	cleaning_stocks(	LLY	)
LNC	<-	cleaning_stocks(	LNC	)
LLTC	<-	cleaning_stocks(	LLTC	)
LKQ	<-	cleaning_stocks(	LKQ	)
LMT	<-	cleaning_stocks(	LMT	)
L	<-	cleaning_stocks(	L	)
LOW	<-	cleaning_stocks(	LOW	)
LYB	<-	cleaning_stocks(	LYB	)
MTB	<-	cleaning_stocks(	MTB	)
MAC	<-	cleaning_stocks(	MAC	)
M	<-	cleaning_stocks(	M	)
MNK	<-	cleaning_stocks(	MNK	)
MRO	<-	cleaning_stocks(	MRO	)
MPC	<-	cleaning_stocks(	MPC	)
MAR	<-	cleaning_stocks(	MAR	)
MMC	<-	cleaning_stocks(	MMC	)
MLM	<-	cleaning_stocks(	MLM	)
MAS	<-	cleaning_stocks(	MAS	)
MA	<-	cleaning_stocks(	MA	)
MAT	<-	cleaning_stocks(	MAT	)
MKC	<-	cleaning_stocks(	MKC	)
MCD	<-	cleaning_stocks(	MCD	)
MCK	<-	cleaning_stocks(	MCK	)
MJN	<-	cleaning_stocks(	MJN	)
MDT	<-	cleaning_stocks(	MDT	)
MRK	<-	cleaning_stocks(	MRK	)
MET	<-	cleaning_stocks(	MET	)
MTD	<-	cleaning_stocks(	MTD	)
KORS	<-	cleaning_stocks(	KORS	)
MCHP	<-	cleaning_stocks(	MCHP	)
MU	<-	cleaning_stocks(	MU	)
MSFT	<-	cleaning_stocks(	MSFT	)
MAA	<-	cleaning_stocks(	MAA	)
MHK	<-	cleaning_stocks(	MHK	)
TAP	<-	cleaning_stocks(	TAP	)
MDLZ	<-	cleaning_stocks(	MDLZ	)
MON	<-	cleaning_stocks(	MON	)
MNST	<-	cleaning_stocks(	MNST	)
MCO	<-	cleaning_stocks(	MCO	)
MS	<-	cleaning_stocks(	MS	)
MSI	<-	cleaning_stocks(	MSI	)
MUR	<-	cleaning_stocks(	MUR	)
MYL	<-	cleaning_stocks(	MYL	)
NDAQ	<-	cleaning_stocks(	NDAQ	)
NOV	<-	cleaning_stocks(	NOV	)
NAVI	<-	cleaning_stocks(	NAVI	)
NTAP	<-	cleaning_stocks(	NTAP	)
NFLX	<-	cleaning_stocks(	NFLX	)
NWL	<-	cleaning_stocks(	NWL	)
NFX	<-	cleaning_stocks(	NFX	)
NEM	<-	cleaning_stocks(	NEM	)
NWSA	<-	cleaning_stocks(	NWSA	)
NWS	<-	cleaning_stocks(	NWS	)
NEE	<-	cleaning_stocks(	NEE	)
NLSN	<-	cleaning_stocks(	NLSN	)
NKE	<-	cleaning_stocks(	NKE	)
NI	<-	cleaning_stocks(	NI	)
NBL	<-	cleaning_stocks(	NBL	)
JWN	<-	cleaning_stocks(	JWN	)
NSC	<-	cleaning_stocks(	NSC	)
NTRS	<-	cleaning_stocks(	NTRS	)
NOC	<-	cleaning_stocks(	NOC	)
NRG	<-	cleaning_stocks(	NRG	)
NUE	<-	cleaning_stocks(	NUE	)
NVDA	<-	cleaning_stocks(	NVDA	)
ORLY	<-	cleaning_stocks(	ORLY	)
OXY	<-	cleaning_stocks(	OXY	)
OMC	<-	cleaning_stocks(	OMC	)
OKE	<-	cleaning_stocks(	OKE	)
ORCL	<-	cleaning_stocks(	ORCL	)
PCAR	<-	cleaning_stocks(	PCAR	)
PH	<-	cleaning_stocks(	PH	)
PDCO	<-	cleaning_stocks(	PDCO	)
PAYX	<-	cleaning_stocks(	PAYX	)
PYPL	<-	cleaning_stocks(	PYPL	)
PNR	<-	cleaning_stocks(	PNR	)
PBCT	<-	cleaning_stocks(	PBCT	)
PEP	<-	cleaning_stocks(	PEP	)
PKI	<-	cleaning_stocks(	PKI	)
PRGO	<-	cleaning_stocks(	PRGO	)
PFE	<-	cleaning_stocks(	PFE	)
PCG	<-	cleaning_stocks(	PCG	)
PM	<-	cleaning_stocks(	PM	)
PSX	<-	cleaning_stocks(	PSX	)
PNW	<-	cleaning_stocks(	PNW	)
PXD	<-	cleaning_stocks(	PXD	)
PNC	<-	cleaning_stocks(	PNC	)
RL	<-	cleaning_stocks(	RL	)
PPG	<-	cleaning_stocks(	PPG	)
PPL	<-	cleaning_stocks(	PPL	)
PX	<-	cleaning_stocks(	PX	)
PCLN	<-	cleaning_stocks(	PCLN	)
PFG	<-	cleaning_stocks(	PFG	)
PG	<-	cleaning_stocks(	PG	)
PGR	<-	cleaning_stocks(	PGR	)
PLD	<-	cleaning_stocks(	PLD	)
PRU	<-	cleaning_stocks(	PRU	)
PEG	<-	cleaning_stocks(	PEG	)
PSA	<-	cleaning_stocks(	PSA	)
PHM	<-	cleaning_stocks(	PHM	)
PVH	<-	cleaning_stocks(	PVH	)
QRVO	<-	cleaning_stocks(	QRVO	)
QCOM	<-	cleaning_stocks(	QCOM	)
PWR	<-	cleaning_stocks(	PWR	)
DGX	<-	cleaning_stocks(	DGX	)
RRC	<-	cleaning_stocks(	RRC	)
RTN	<-	cleaning_stocks(	RTN	)
O	<-	cleaning_stocks(	O	)
RHT	<-	cleaning_stocks(	RHT	)
REG	<-	cleaning_stocks(	REG	)
REGN	<-	cleaning_stocks(	REGN	)
RF	<-	cleaning_stocks(	RF	)
RSG	<-	cleaning_stocks(	RSG	)
RAI	<-	cleaning_stocks(	RAI	)
RHI	<-	cleaning_stocks(	RHI	)
ROK	<-	cleaning_stocks(	ROK	)
COL	<-	cleaning_stocks(	COL	)
ROP	<-	cleaning_stocks(	ROP	)
ROST	<-	cleaning_stocks(	ROST	)
RCL	<-	cleaning_stocks(	RCL	)
R	<-	cleaning_stocks(	R	)
SPGI	<-	cleaning_stocks(	SPGI	)
CRM	<-	cleaning_stocks(	CRM	)
SCG	<-	cleaning_stocks(	SCG	)
SLB	<-	cleaning_stocks(	SLB	)
SNI	<-	cleaning_stocks(	SNI	)
STX	<-	cleaning_stocks(	STX	)
SEE	<-	cleaning_stocks(	SEE	)
SRE	<-	cleaning_stocks(	SRE	)
SHW	<-	cleaning_stocks(	SHW	)
SIG	<-	cleaning_stocks(	SIG	)
SPG	<-	cleaning_stocks(	SPG	)
SWKS	<-	cleaning_stocks(	SWKS	)
SLG	<-	cleaning_stocks(	SLG	)
SNA	<-	cleaning_stocks(	SNA	)
SO	<-	cleaning_stocks(	SO	)
LUV	<-	cleaning_stocks(	LUV	)
SWN	<-	cleaning_stocks(	SWN	)
SWK	<-	cleaning_stocks(	SWK	)
SPLS	<-	cleaning_stocks(	SPLS	)
SBUX	<-	cleaning_stocks(	SBUX	)
STT	<-	cleaning_stocks(	STT	)
SRCL	<-	cleaning_stocks(	SRCL	)
SYK	<-	cleaning_stocks(	SYK	)
STI	<-	cleaning_stocks(	STI	)
SYMC	<-	cleaning_stocks(	SYMC	)
SYF	<-	cleaning_stocks(	SYF	)
SYY	<-	cleaning_stocks(	SYY	)
TROW	<-	cleaning_stocks(	TROW	)
TGT	<-	cleaning_stocks(	TGT	)
TEL	<-	cleaning_stocks(	TEL	)
TGNA	<-	cleaning_stocks(	TGNA	)
TDC	<-	cleaning_stocks(	TDC	)
TSO	<-	cleaning_stocks(	TSO	)
TXN	<-	cleaning_stocks(	TXN	)
TXT	<-	cleaning_stocks(	TXT	)
BK	<-	cleaning_stocks(	BK	)
CLX	<-	cleaning_stocks(	CLX	)
COO	<-	cleaning_stocks(	COO	)
HSY	<-	cleaning_stocks(	HSY	)
MOS	<-	cleaning_stocks(	MOS	)
TRV	<-	cleaning_stocks(	TRV	)
DIS	<-	cleaning_stocks(	DIS	)
TMO	<-	cleaning_stocks(	TMO	)
TIF	<-	cleaning_stocks(	TIF	)
TWX	<-	cleaning_stocks(	TWX	)
TJX	<-	cleaning_stocks(	TJX	)
TMK	<-	cleaning_stocks(	TMK	)
TSS	<-	cleaning_stocks(	TSS	)
TSCO	<-	cleaning_stocks(	TSCO	)
TDG	<-	cleaning_stocks(	TDG	)
RIG	<-	cleaning_stocks(	RIG	)
TRIP	<-	cleaning_stocks(	TRIP	)
FOXA	<-	cleaning_stocks(	FOXA	)
FOX	<-	cleaning_stocks(	FOX	)
TSN	<-	cleaning_stocks(	TSN	)
USB	<-	cleaning_stocks(	USB	)
UDR	<-	cleaning_stocks(	UDR	)
ULTA	<-	cleaning_stocks(	ULTA	)
UA	<-	cleaning_stocks(	UA	)
UAA	<-	cleaning_stocks(	UAA	)
UNP	<-	cleaning_stocks(	UNP	)
UAL	<-	cleaning_stocks(	UAL	)
UNH	<-	cleaning_stocks(	UNH	)
UPS	<-	cleaning_stocks(	UPS	)
URI	<-	cleaning_stocks(	URI	)
UTX	<-	cleaning_stocks(	UTX	)
UHS	<-	cleaning_stocks(	UHS	)
UNM	<-	cleaning_stocks(	UNM	)
URBN	<-	cleaning_stocks(	URBN	)
VFC	<-	cleaning_stocks(	VFC	)
VLO	<-	cleaning_stocks(	VLO	)
VAR	<-	cleaning_stocks(	VAR	)
VTR	<-	cleaning_stocks(	VTR	)
VRSN	<-	cleaning_stocks(	VRSN	)
VRSK	<-	cleaning_stocks(	VRSK	)
VZ	<-	cleaning_stocks(	VZ	)
VRTX	<-	cleaning_stocks(	VRTX	)
VIAB	<-	cleaning_stocks(	VIAB	)
V	<-	cleaning_stocks(	V	)
VNO	<-	cleaning_stocks(	VNO	)
VMC	<-	cleaning_stocks(	VMC	)
WMT	<-	cleaning_stocks(	WMT	)
WBA	<-	cleaning_stocks(	WBA	)
WM	<-	cleaning_stocks(	WM	)
WAT	<-	cleaning_stocks(	WAT	)
WEC	<-	cleaning_stocks(	WEC	)
WFC	<-	cleaning_stocks(	WFC	)
HCN	<-	cleaning_stocks(	HCN	)
WDC	<-	cleaning_stocks(	WDC	)
WU	<-	cleaning_stocks(	WU	)
WRK	<-	cleaning_stocks(	WRK	)
WY	<-	cleaning_stocks(	WY	)
WHR	<-	cleaning_stocks(	WHR	)
WFM	<-	cleaning_stocks(	WFM	)
WMB	<-	cleaning_stocks(	WMB	)
WLTW	<-	cleaning_stocks(	WLTW	)
WYN	<-	cleaning_stocks(	WYN	)
WYNN	<-	cleaning_stocks(	WYNN	)
XEL	<-	cleaning_stocks(	XEL	)
XRX	<-	cleaning_stocks(	XRX	)
XLNX	<-	cleaning_stocks(	XLNX	)
XL	<-	cleaning_stocks(	XL	)
XYL	<-	cleaning_stocks(	XYL	)
YHOO	<-	cleaning_stocks(	YHOO	)
YUM	<-	cleaning_stocks(	YUM	)
ZBH	<-	cleaning_stocks(	ZBH	)
ZION	<-	cleaning_stocks(	ZION	)
ZTS	<-	cleaning_stocks(	ZTS	)


rm(SP500);rm(endDate);rm(startDate);rm(TICKERS);rm(cleaning_stocks);rm(i)

STOCKS<-do.call(rbind, eapply(.GlobalEnv,function(x) data.frame(date=index(x), coredata(x))))

STOCKS$Dollar.chg <- (STOCKS$Adj.Close-STOCKS$Open)
STOCKS$Pct.chg <- (STOCKS$Dollar.chg/STOCKS$Open)
STOCKS$Volatility <- (STOCKS$High-STOCKS$Low)/STOCKS$Adj.Close

STOCKS$RISE <- ifelse(STOCKS$Dollar.chg > 0 ,1,0)
#STOCKS$up.down.lag <- unlist(tapply(STOCK[,"RISE"],STOCK[,"Ticker"], function(x) c(x[-1],NA)))
#STOCKS$ticker<- as.data.frame(strsplit(as.character(STOCKS$Ticker),'.',fixed=TRUE))
STOCKS$ticker<-NULL
STOCKS<- add_rownames(STOCKS, "ticker")

cleanText <- function(x) {
  # tolower
  #x = tolower(x)
  # remove rt
  #x = gsub("rt", "", x)
  # remove at
  x = gsub("@\\w+", "", x)
  # remove punctuation
  x = gsub("[[:punct:]]", "", x)
  # remove control characters
  x <-  gsub('[[:cntrl:]]', '', x)
  # remove numbers
  x = gsub("[[:digit:]]", "", x)
  # remove links http
  x = gsub("http\\w+",  "", x)
  # remove tabs
  x = gsub("[ |\t]{2,}", " ", x)
  # remove new lines
  x = gsub("[ |\n]{1,}", " ", x)
  # remove blank spaces at the beginning
  x = gsub("^ ", "", x)
  # remove blank spaces at the end
  x = gsub(" $", "", x)
  return(x)
}
STOCKS$ticker<-cleanText(STOCKS$ticker)
STOCKS$date<- NULL
colnames(STOCKS)[2] <- "date"
setwd("C:/Users/User/Documents/R")
write.csv(STOCKS, file="STOCKS_Prices_28_31.csv")
